name: ${PROJECT_NAME}-dev

services:
  db:
    image: "postgres:${POSTGRES_VERSION}"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 5s
    networks:
      - internal
    ports:
      - "${PORT_DB}:${PORT_DB}"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
        PORT_BACK: ${PORT_BACK}
    env_file:
      - ./backend/.env.dev
    volumes:
      - ./backend:/app:rw
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
#    ports:
#      - "${PORT_BACK}:${PORT_BACK}"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
      args:
        NODE_VERSION: ${NODE_VERSION}
        PORT_FRONT: ${PORT_FRONT}
    env_file:
      - ./frontend/.env.dev
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      npm_config_cache: "/npm_cache"
    volumes:
      - ./frontend:/app:rw,delegated
      - frontend_node_modules:/app/node_modules:rw
      - frontend_npm_cache:/npm_cache
    networks:
      - internal
#    ports:
#      - "${PORT_FRONT}:${PORT_FRONT}"
    stdin_open: true
    tty: true
    command: ["sh","-lc","npm run dev -- --host 0.0.0.0 --port $PORT_FRONT --strictPort"]

  reverseproxy:
    build:
      context: ./reverseProxy
      dockerfile: Dockerfile
      target: dev
      args:
        NGX_VERSION: ${NGX_VERSION}
    environment:
      PORT_FRONT: ${PORT_FRONT}
      PORT_BACK: ${PORT_BACK}
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost/healthz || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 5s
    networks:
      - internal
      - edge
    ports:
      - "${PORT_NGX}:80"

volumes:
  pgdata:
  frontend_node_modules:
  frontend_npm_cache:


networks:
  internal:
    driver: bridge
  edge:
    driver: bridge