# Generated by Django 5.2.7 on 2025-10-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
