# Generated by Django 5.2.7 on 2025-10-08 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0002_alter_users_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roles',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='shifts',
            table='shifts',
        ),
        migrations.AlterModelTable(
            name='teams',
            table='teams',
        ),
    ]
