# Generated by Django 5.2.7 on 2025-10-09 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0004_users_groups_users_is_active_users_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifts',
            name='user_id',
        ),
        migrations.AddField(
            model_name='shifts',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
