# Generated by Django 5.2.7 on 2025-10-15 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0005_remove_shifts_user_id_shifts_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weekday', models.PositiveSmallIntegerField()),
                ('start_local_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('apply_to_whole_team', models.BooleanField(default=False)),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='shift_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shift_rules',
            },
        ),
        migrations.CreateModel(
            name='ShiftException',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('is_skipped', models.BooleanField(default=False)),
                ('override_start_local_time', models.TimeField(blank=True, null=True)),
                ('override_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='db_manager.shiftrule')),
            ],
            options={
                'db_table': 'shift_exceptions',
            },
        ),
        migrations.AddField(
            model_name='shifts',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='db_manager.shiftrule'),
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('default_duration_minutes', models.PositiveIntegerField()),
                ('timezone', models.CharField(default='Europe/Paris', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shift_templates', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_manager.roles')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='db_manager.teams')),
            ],
            options={
                'db_table': 'shift_templates',
            },
        ),
        migrations.AddField(
            model_name='shiftrule',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='db_manager.shifttemplate'),
        ),
        migrations.AddField(
            model_name='shifts',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='db_manager.shifttemplate'),
        ),
        migrations.AddIndex(
            model_name='shifts',
            index=models.Index(fields=['user', 'start_time'], name='shifts_user_id_07613e_idx'),
        ),
        migrations.AddConstraint(
            model_name='shifts',
            constraint=models.UniqueConstraint(fields=('user', 'start_time', 'end_time'), name='no_overlap_shifts_same_user'),
        ),
        migrations.AlterUniqueTogether(
            name='shiftexception',
            unique_together={('rule', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='shifttemplate',
            unique_together={('team', 'name')},
        ),
        migrations.AddIndex(
            model_name='shiftrule',
            index=models.Index(fields=['weekday', 'effective_from', 'effective_to'], name='shift_rules_weekday_409a34_idx'),
        ),
    ]
